# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, index old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and index random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across index environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  bot_token: 294560170:AAFaB9cQ-hCzQEfYNr6z30gD2K7FeDZ1gVQ
  api_ai_token: 5be01c3c53364cf786578a4774136763
  secret_key_base: b76119aa5db9eff7c8478773bb365ec1b87d2d5fb5412d0f7ee85517ff123facdc64d5d713267b61dfa5f443dd2b524822226772b76d33a7efee8e130ca95706

test:
  secret_key_base: 1a79eab863a4f35ac74d27a6202868510473ac92fad47e5b68bb5172388ac91f8f34decabfdb886556b9cb307ca45bfbecfa703f314b37278e758ec5107551cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: b76119aa5db9eff7c8478773bb365ec1b87d2d5fb5412d0f7ee85517ff123facdc64d5d713267b61dfa5f443dd2b524822226772b76d33a7efee8e130ca95706
